

// Do not edit directly
// Generated on Tue, 13 Jun 2023 12:43:26 GMT



package br.com.cogna.pegasusdesignsystemandroid.sofia;

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.*

object SofiaColors {
  val sofia_color_refs_warning_warning_99 = Color(0xFFfffbf5)
  val sofia_color_refs_warning_warning_95 = Color(0xFFfff0df)
  val sofia_color_refs_warning_warning_90 = Color(0xFFffe6c9)
  val sofia_color_refs_warning_warning_80 = Color(0xFFffd399)
  val sofia_color_refs_warning_warning_70 = Color(0xFFffbc66)
  val sofia_color_refs_warning_warning_60 = Color(0xFFffa433)
  val sofia_color_refs_warning_warning_50 = Color(0xFFff8a00)
  val sofia_color_refs_warning_warning_40 = Color(0xFFdf7900)
  val sofia_color_refs_warning_warning_30 = Color(0xFFbf6800)
  val sofia_color_refs_warning_warning_20 = Color(0xFF9f5600)
  val sofia_color_refs_warning_warning_100 = Color(0xFFffffff)
  val sofia_color_refs_warning_warning_10 = Color(0xFF804500)
  val sofia_color_refs_warning_warning_0 = Color(0xFF291807)
  val sofia_color_refs_success_success_99 = Color(0xFFf5fffd)
  val sofia_color_refs_success_success_95 = Color(0xFFe8faf6)
  val sofia_color_refs_success_success_90 = Color(0xFFe0f0ed)
  val sofia_color_refs_success_success_80 = Color(0xFF99e2cd)
  val sofia_color_refs_success_success_70 = Color(0xFF66caae)
  val sofia_color_refs_success_success_60 = Color(0xFF33ab8c)
  val sofia_color_refs_success_success_50 = Color(0xFF008566)
  val sofia_color_refs_success_success_40 = Color(0xFF007358)
  val sofia_color_refs_success_success_30 = Color(0xFF006049)
  val sofia_color_refs_success_success_20 = Color(0xFF004d3a)
  val sofia_color_refs_success_success_100 = Color(0xFFffffff)
  val sofia_color_refs_success_success_10 = Color(0xFF00392b)
  val sofia_color_refs_success_success_0 = Color(0xFF000000)
  val sofia_color_refs_secondary_secondary_99 = Color(0xFFfefbfa)
  val sofia_color_refs_secondary_secondary_95 = Color(0xFFfcede9)
  val sofia_color_refs_secondary_secondary_90 = Color(0xFFfcd8cc)
  val sofia_color_refs_secondary_secondary_80 = Color(0xFFfebda9)
  val sofia_color_refs_secondary_secondary_70 = Color(0xFFff9c7c)
  val sofia_color_refs_secondary_secondary_60 = Color(0xFFff6d46)
  val sofia_color_refs_secondary_secondary_50 = Color(0xFFee4623)
  val sofia_color_refs_secondary_secondary_40 = Color(0xFFc53a1d)
  val sofia_color_refs_secondary_secondary_30 = Color(0xFF932b15)
  val sofia_color_refs_secondary_secondary_20 = Color(0xFF641f10)
  val sofia_color_refs_secondary_secondary_100 = Color(0xFFffffff)
  val sofia_color_refs_secondary_secondary_0 = Color(0xFF000000)
  val sofia_color_refs_primary_primary_99 = Color(0xFFf8f8ff)
  val sofia_color_refs_primary_primary_95 = Color(0xFFeff0ff)
  val sofia_color_refs_primary_primary_90 = Color(0xFFdadcff)
  val sofia_color_refs_primary_primary_80 = Color(0xFFacb1ff)
  val sofia_color_refs_primary_primary_70 = Color(0xFF7389ff)
  val sofia_color_refs_primary_primary_60 = Color(0xFF3969eb)
  val sofia_color_refs_primary_primary_50 = Color(0xFF004ecc)
  val sofia_color_refs_primary_primary_40 = Color(0xFF0041af)
  val sofia_color_refs_primary_primary_30 = Color(0xFF003491)
  val sofia_color_refs_primary_primary_20 = Color(0xFF002871)
  val sofia_color_refs_primary_primary_100 = Color(0xFFffffff)
  val sofia_color_refs_primary_primary_10 = Color(0xFF001f50)
  val sofia_color_refs_primary_primary_0 = Color(0xFF000000)
  val sofia_color_refs_neutrals_neutral_99 = Color(0xFFfbfbff)
  val sofia_color_refs_neutrals_neutral_95 = Color(0xFFeff0f4)
  val sofia_color_refs_neutrals_neutral_90 = Color(0xFFdee1e5)
  val sofia_color_refs_neutrals_neutral_80 = Color(0xFFc5c7ca)
  val sofia_color_refs_neutrals_neutral_70 = Color(0xFFaaaaae)
  val sofia_color_refs_neutrals_neutral_60 = Color(0xFF909194)
  val sofia_color_refs_neutrals_neutral_50 = Color(0xFF757579)
  val sofia_color_refs_neutrals_neutral_30 = Color(0xFF464649)
  val sofia_color_refs_neutrals_neutral_20 = Color(0xFF303033)
  val sofia_color_refs_neutrals_neutral_100 = Color(0xFFffffff)
  val sofia_color_refs_neutrals_neutral_10 = Color(0xFF1b1b1f)
  val sofia_color_refs_neutrals_neutral_0 = Color(0xFF000000)
  val sofia_color_refs_info_info_99 = Color(0xFFf9f6fc)
  val sofia_color_refs_info_info_95 = Color(0xFFf1eff4)
  val sofia_color_refs_info_info_90 = Color(0xFFe2dee8)
  val sofia_color_refs_info_info_80 = Color(0xFFd2cadc)
  val sofia_color_refs_info_info_70 = Color(0xFFbcb2cd)
  val sofia_color_refs_info_info_60 = Color(0xFFa697bd)
  val sofia_color_refs_info_info_50 = Color(0xFF9484b0)
  val sofia_color_refs_info_info_40 = Color(0xFF746199)
  val sofia_color_refs_info_info_30 = Color(0xFF574583)
  val sofia_color_refs_info_info_20 = Color(0xFF3d2e68)
  val sofia_color_refs_info_info_100 = Color(0xFFffffff)
  val sofia_color_refs_info_info_10 = Color(0xFF231b3a)
  val sofia_color_refs_info_info_0 = Color(0xFF000000)
  val sofia_color_refs_error_error_99 = Color(0xFFfffbf9)
  val sofia_color_refs_error_error_95 = Color(0xFFfceeee)
  val sofia_color_refs_error_error_90 = Color(0xFFf9dedc)
  val sofia_color_refs_error_error_80 = Color(0xFFf2b8b5)
  val sofia_color_refs_error_error_70 = Color(0xFFec928e)
  val sofia_color_refs_error_error_60 = Color(0xFFe46962)
  val sofia_color_refs_error_error_50 = Color(0xFFdc362e)
  val sofia_color_refs_error_error_40 = Color(0xFFb3261e)
  val sofia_color_refs_error_error_30 = Color(0xFF8c1d18)
  val sofia_color_refs_error_error_20 = Color(0xFF601410)
  val sofia_color_refs_error_error_100 = Color(0xFFffffff)
  val sofia_color_refs_error_error_10 = Color(0xFF410e0b)
  val sofia_color_light_theme_others_stroke = Color(0xFFaeaaae)
  val sofia_color_light_theme_others_rating = Color(0xFFffa433)
  val sofia_color_light_theme_others_divider = Color(0xFFe6e1e5)
  val sofia_color_light_theme_others_backdrop = Color(0xFF1c1b1f)
  val sofia_color_light_theme_neutral_surface = Color(0xFFedeff1)
  val sofia_color_light_theme_neutral_on_surface = Color(0xFF1c1b1f)
  val sofia_color_light_theme_neutral_on_background2 = Color(0xFF787579)
  val sofia_color_light_theme_neutral_on_background = Color(0xFF1c1b1f)
  val sofia_color_light_theme_neutral_background = Color(0xFFffffff)
  val sofia_color_light_theme_brand_secondary_secondary_main = Color(0xFF932b15)
  val sofia_color_light_theme_brand_secondary_secondary_light = Color(0xFFff6d46)
  val sofia_color_light_theme_brand_secondary_secondary_dark = Color(0xFF641f10)
  val sofia_color_light_theme_brand_secondary_secondary_container = Color(0xFFfebda9)
  val sofia_color_light_theme_brand_secondary_on_secondary_main = Color(0xFFffffff)
  val sofia_color_light_theme_brand_secondary_on_secondary_light = Color(0xFF000000)
  val sofia_color_light_theme_brand_secondary_on_secondary_dark = Color(0xFFffffff)
  val sofia_color_light_theme_brand_secondary_on_secondary_container = Color(0xFF000000)
  val sofia_color_light_theme_brand_primary_primary_main = Color(0xFF0041af)
  val sofia_color_light_theme_brand_primary_primary_light = Color(0xFF004ecc)
  val sofia_color_light_theme_brand_primary_primary_dark = Color(0xFF002871)
  val sofia_color_light_theme_brand_primary_primary_container = Color(0xFFeff5ff)
  val sofia_color_light_theme_brand_primary_on_primary_main = Color(0xFFffffff)
  val sofia_color_light_theme_brand_primary_on_primary_light = Color(0xFFffffff)
  val sofia_color_light_theme_brand_primary_on_primary_dark = Color(0xFFffffff)
  val sofia_color_light_theme_brand_primary_on_primary_container = Color(0xFF002871)
  val sofia_color_light_theme_alerts_warning_container = Color(0xFFffe6c9)
  val sofia_color_light_theme_alerts_warning = Color(0xFF804500)
  val sofia_color_light_theme_alerts_success_container = Color(0xFFe0f0ed)
  val sofia_color_light_theme_alerts_success = Color(0xFF006049)
  val sofia_color_light_theme_alerts_on_warning_container = Color(0xFF291807)
  val sofia_color_light_theme_alerts_on_warning = Color(0xFFffffff)
  val sofia_color_light_theme_alerts_on_success_container = Color(0xFF00392b)
  val sofia_color_light_theme_alerts_on_success = Color(0xFFffffff)
  val sofia_color_light_theme_alerts_on_info_container = Color(0xFF231b3a)
  val sofia_color_light_theme_alerts_on_info = Color(0xFFffffff)
  val sofia_color_light_theme_alerts_on_error_container = Color(0xFF601410)
  val sofia_color_light_theme_alerts_on_error = Color(0xFFffffff)
  val sofia_color_light_theme_alerts_info_container = Color(0xFFf1eff4)
  val sofia_color_light_theme_alerts_info = Color(0xFF574583)
  val sofia_color_light_theme_alerts_error_container = Color(0xFFfceeee)
  val sofia_color_light_theme_alerts_error = Color(0xFF8c1d18)
}
